import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NavBar } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ecommerce Project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  productlist,
}: {
  children: React.ReactNode;
  productlist: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NavBar />
        {children}
        {/* {productlist} */}
      </body>
    </html>
  );
}
